# Generated by Django 4.0.6 on 2022-07-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webocr', '0004_product_intrested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='intrested',
            new_name='interested',
        ),
    ]
