# Generated by Django 4.0.6 on 2022-07-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webocr', '0005_rename_intrested_product_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='order',
            name='tot_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
